Update references to 'activity' to reflect new project
CSIS-iLab/poni-timeline pull request #17
Opened 2023-10-04 13:14 UTC by mariel-delagarza

Update references to "Activity" to be "timelineEvent" -- `activity` was a holdover from the `database-table-template`.

Use `timelineEvent` to reflect original project idea and distinguish between browser events/event handlers.

2023-10-04 18:00 UTC, jdromero88 requested changes, later dismissed
Thank you for working on this @mariel-delagarza! I found out this is breaking the sort functionality.
![image](https://github.com/CSIS-iLab/poni-table/assets/51330062/5ea6b319-590f-4348-8bf2-c37d0de285d2)

On the Table.svelte component In line 159
```html 
class="table__cell--header__container table__cell--header__container__{name
.toLowerCase()
.split(' ')
.join('-')}
```
Here we are looping through the header names, so the div it's being rendered with a class `table__cell--header__container__event`

Also for consistency, let's try to keep the class names with kebab-case please.
I left you a few comments below.

2023-10-04 18:00 UTC, jdromero88 commented on src/components/Table.svelte
> +      ".table__cell--header__container__timelineEvent",
I suggest changing this to ```".table__cell--header__container__event"```

2023-10-04 18:00 UTC, jdromero88 commented on src/scss/components/_table.scss
> +      &__container__timelineEvent,
I suggest changing this to ```&__container__event```

2023-10-05 15:43 UTC, mariel-delagarza commented
Gracias! I made these class name changes (to `container__event`) and that fixed the sort functionality 👍

2023-10-05 15:45 UTC, merged